services:
  redis:
    image: redis:alpine
    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

    volumes:
      - .docker/volumes/redis_data:/data

    command: ['redis-server', '--save', '60', '1']
    ports:
      - ${APP_REDIS_HOST_ADDRESS}:${APP_REDIS_HOST_PORT}:6379
